name: godot-4-0
base: core22
version: 4.0-beta8
summary: The game engine you've been waiting for.
description: |
  The Godot Engine is a free, all-in-one, cross-platform game engine that makes it easy for you to create 2D and 3D games.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
compression: lzo

parts:
  godot-4-0:
    plugin: dump
    source: https://downloads.tuxfamily.org/godotengine/4.0/beta8/mono/Godot_v$SNAPCRAFT_PROJECT_VERSION_mono_linux_x86_64.zip
    override-build: |
      craftctl default
      mv Godot* tmp/
      mv tmp/* $CRAFT_PART_INSTALL/
      rmdir tmp

  desktop-file:
    plugin: dump
    source: desktop-file
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp * $CRAFT_PART_INSTALL/meta/gui

  cleanup:
    after: [ godot-4-0 ]
    plugin: nil
    build-snaps: [ gnome-42-2204 ]
    override-prime: |
        set -eux
        cd /snap/gnome-42-2204/current
        find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;

apps:
  godot-4-0:
    extensions: [gnome]
    command: Godot_v$SNAPCRAFT_PROJECT_VERSION_mono_linux.x86_64
    desktop: meta/gui/godot-4-0.desktop
    plugs:
      - home
      - network
      - audio-playback
      - audio-record
      - removable-media
    environment:
      HOME: $SNAP_USER_COMMON
