name: godot-3-5
base: core22
version: 3.5.1
summary: The game engine you've been waiting for.
description: |
  The Godot Engine is a free, all-in-one, cross-platform game engine that makes it easy for you to create 2D and 3D games.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
compression: lzo

parts:
  dotnet:
    plugin: nil
    stage-packages:
      - dotnet-sdk-6.0
      - dotnet-runtime-6.0
  godot-3-5:
    plugin: dump
    source: https://downloads.tuxfamily.org/godotengine/$SNAPCRAFT_PROJECT_VERSION/mono/Godot_v$SNAPCRAFT_PROJECT_VERSION-stable_mono_x11_64.zip
    override-build: |
      craftctl default
      mv Godot* tmp/
      mv tmp/* $CRAFT_PART_INSTALL/
      rmdir tmp

  desktop-file:
    plugin: dump
    source: desktop-file
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp * $CRAFT_PART_INSTALL/meta/gui

  cleanup:
    after: [ godot-3-5 ]
    plugin: nil
    build-snaps: [ gnome-42-2204 ]
    override-prime: |
        set -eux
        cd /snap/gnome-42-2204/current
        find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;

apps:
  godot-3-5:
    extensions: [gnome]
    command: Godot_v$SNAPCRAFT_PROJECT_VERSION-stable_mono_x11.64
    desktop: meta/gui/godot-3-5.desktop
    plugs:
      - home
      - network
      - audio-playback
      - audio-record
      - removable-media
    environment:
      HOME: $SNAP_USER_COMMON
